language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r server_script/SunScreenServer/requirements.txt
# command to run tests
script:
  - cd server_script
  - python -m unittest discover  -p "*_test.py" -s tests
